site_name: Nested Ragged Tensors
repo_url: https://github.com/mmcdermott/nested_ragged_tensors
site_description: Documentation for the nested-ragged-tensors package
site_author: Matthew McDermott

nav:
  - Home: index.md
  - API: api/
  - Issues: https://github.com/mmcdermott/nested_ragged_tensors/issues

theme:
  name: material
  locale: en

markdown_extensions:
  - smarty
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings
  - git-authors
  - git-revision-date-localized
