name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, "release/*", "dev"]

jobs:
  run_tests_ubuntu:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
      fail-fast: false

    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Setup package
        uses: ./.github/actions/setup
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        run: >
          uv run pytest -v --doctest-modules --cov=src --junitxml=junit.xml -s
          --ignore=benchmark --ignore=sample_dataset_builder --ignore=docs

      - name: Upload coverage to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          report_type: test_results

      - name: Check README code snippets
        run: |
          uv run python -m doctest README.md
